<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FiBwT5OService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.FiBwT5O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FiBwT5O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'compagnie' => ['privates', '.errored..service_locator.FiBwT5O.App\\Entity\\Compagnie', NULL, 'Cannot autowire service ".service_locator.FiBwT5O": it needs an instance of "App\\Entity\\Compagnie" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'compagnie' => 'App\\Entity\\Compagnie',
            'entityManager' => '?',
        ]);
    }
}
