<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ElXdKcMService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.elXdKcM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.elXdKcM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'compagnie' => ['privates', '.errored..service_locator.elXdKcM.App\\Entity\\Compagnie', NULL, 'Cannot autowire service ".service_locator.elXdKcM": it needs an instance of "App\\Entity\\Compagnie" but this type has been excluded in "config/services.yaml".'],
        ], [
            'compagnie' => 'App\\Entity\\Compagnie',
        ]);
    }
}
