<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiParticipationControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\ApiParticipationController' shared autowired service.
     *
     * @return \App\Controller\Api\ApiParticipationController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\ApiParticipationController'] = $instance = new \App\Controller\Api\ApiParticipationController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\CompagnieRepository'] ?? $container->load('getCompagnieRepositoryService')), ($container->privates['App\\Repository\\DisciplineRepository'] ?? $container->load('getDisciplineRepositoryService')), ($container->privates['App\\Service\\AllRepositories'] ?? $container->load('getAllRepositoriesService')), ($container->privates['App\\Service\\GestionMedia'] ??= new \App\Service\GestionMedia((\dirname(__DIR__, 4).'/public/upload/participants'), (\dirname(__DIR__, 4).'/public/upload/adhesion'), (\dirname(__DIR__, 4).'/public/upload/sponsors'))), ($container->privates['App\\Repository\\CompetirRepository'] ?? $container->load('getCompetirRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\ApiParticipationController', $container));

        return $instance;
    }
}
