<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdhesionTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AdhesionType' shared autowired service.
     *
     * @return \App\Form\AdhesionType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AdhesionType'] = new \App\Form\AdhesionType();
    }
}
