<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminUserControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Backend\AdminUserController' shared autowired service.
     *
     * @return \App\Controller\Backend\AdminUserController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Backend\\AdminUserController'] = $instance = new \App\Controller\Backend\AdminUserController(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->privates['App\\Service\\AllRepositories'] ?? $container->load('getAllRepositoriesService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Backend\\AdminUserController', $container));

        return $instance;
    }
}
