<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAllRepositoriesService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\AllRepositories' shared autowired service.
     *
     * @return \App\Service\AllRepositories
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\AllRepositories'] = new \App\Service\AllRepositories(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\DisciplineRepository'] ?? $container->load('getDisciplineRepositoryService')), ($container->privates['App\\Repository\\CompagnieRepository'] ?? $container->load('getCompagnieRepositoryService')), ($container->privates['App\\Repository\\ParticipantRepository'] ?? $container->load('getParticipantRepositoryService')), ($container->privates['App\\Repository\\JoueurRepository'] ?? $container->load('getJoueurRepositoryService')), ($container->privates['App\\Repository\\MembreRepository'] ?? $container->load('getMembreRepositoryService')), ($container->privates['App\\Repository\\AbonnementRepository'] ?? $container->load('getAbonnementRepositoryService')));
    }
}
