<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiSponsoringControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\ApiSponsoringController' shared autowired service.
     *
     * @return \App\Controller\Api\ApiSponsoringController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\ApiSponsoringController'] = $instance = new \App\Controller\Api\ApiSponsoringController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\GestionMedia'] ??= new \App\Service\GestionMedia((\dirname(__DIR__, 4).'/public/upload/participants'), (\dirname(__DIR__, 4).'/public/upload/adhesion'), (\dirname(__DIR__, 4).'/public/upload/sponsors'))), ($container->privates['App\\Repository\\SponsorRepository'] ?? $container->load('getSponsorRepositoryService')), ($container->privates['App\\Service\\Utilities'] ?? $container->load('getUtilitiesService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\ApiSponsoringController', $container));

        return $instance;
    }
}
