<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiDisciplineControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\ApiDisciplineController' shared autowired service.
     *
     * @return \App\Controller\Api\ApiDisciplineController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\ApiDisciplineController'] = $instance = new \App\Controller\Api\ApiDisciplineController(($container->privates['App\\Service\\AllRepositories'] ?? $container->load('getAllRepositoriesService')), ($container->privates['serializer'] ?? self::getSerializerService($container)), ($container->privates['App\\Repository\\MembreRepository'] ?? $container->load('getMembreRepositoryService')), ($container->privates['App\\Repository\\AbonnementRepository'] ?? $container->load('getAbonnementRepositoryService')), ($container->privates['App\\Repository\\DisciplineRepository'] ?? $container->load('getDisciplineRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\GestionMedia'] ??= new \App\Service\GestionMedia((\dirname(__DIR__, 4).'/public/upload/participants'), (\dirname(__DIR__, 4).'/public/upload/adhesion'), (\dirname(__DIR__, 4).'/public/upload/sponsors'))), ($container->privates['App\\Repository\\ParticipantRepository'] ?? $container->load('getParticipantRepositoryService')), ($container->privates['App\\Repository\\CompetirRepository'] ?? $container->load('getCompetirRepositoryService')), ($container->privates['App\\Repository\\JoueurRepository'] ?? $container->load('getJoueurRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\ApiDisciplineController', $container));

        return $instance;
    }
}
