<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppFormAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\AppFormAuthenticator' shared autowired service.
     *
     * @return \App\Security\AppFormAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\AppFormAuthenticator'] = new \App\Security\AppFormAuthenticator(($container->services['router'] ?? self::getRouterService($container)), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
