<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiDisciplineSupplementaireControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\ApiDisciplineSupplementaireController' shared autowired service.
     *
     * @return \App\Controller\Api\ApiDisciplineSupplementaireController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\ApiDisciplineSupplementaireController'] = $instance = new \App\Controller\Api\ApiDisciplineSupplementaireController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['serializer'] ?? self::getSerializerService($container)), ($container->privates['App\\Repository\\AbonnementRepository'] ?? $container->load('getAbonnementRepositoryService')), ($container->privates['App\\Repository\\MembreRepository'] ?? $container->load('getMembreRepositoryService')), ($container->privates['App\\Repository\\DisciplineRepository'] ?? $container->load('getDisciplineRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\ApiDisciplineSupplementaireController', $container));

        return $instance;
    }
}
