<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiScientifiqueControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\ApiScientifiqueController' shared autowired service.
     *
     * @return \App\Controller\Api\ApiScientifiqueController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\ApiScientifiqueController'] = $instance = new \App\Controller\Api\ApiScientifiqueController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\EtudiantRepository'] ?? $container->load('getEtudiantRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\ApiScientifiqueController', $container));

        return $instance;
    }
}
