<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdhesionService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.FZNIpPR.App\Entity\Adhesion' shared service.
     *
     * @return \App\Entity\Adhesion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FZNIpPR": it needs an instance of "App\\Entity\\Adhesion" but this type has been excluded in "config/services.yaml".');
    }
}
