<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackendDemandeSponsorControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Backend\BackendDemandeSponsorController' shared autowired service.
     *
     * @return \App\Controller\Backend\BackendDemandeSponsorController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Backend\\BackendDemandeSponsorController'] = $instance = new \App\Controller\Backend\BackendDemandeSponsorController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\SponsorRepository'] ?? $container->load('getSponsorRepositoryService')), ($container->privates['App\\Service\\Utilities'] ?? $container->load('getUtilitiesService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Backend\\BackendDemandeSponsorController', $container));

        return $instance;
    }
}
