<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackendDisciplineControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Backend\BackendDisciplineController' shared autowired service.
     *
     * @return \App\Controller\Backend\BackendDisciplineController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Backend\\BackendDisciplineController'] = $instance = new \App\Controller\Backend\BackendDisciplineController(($container->privates['App\\Service\\AllRepositories'] ?? $container->load('getAllRepositoriesService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Backend\\BackendDisciplineController', $container));

        return $instance;
    }
}
