<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackendAbonnementSuiteControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Backend\BackendAbonnementSuiteController' shared autowired service.
     *
     * @return \App\Controller\Backend\BackendAbonnementSuiteController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Backend\\BackendAbonnementSuiteController'] = $instance = new \App\Controller\Backend\BackendAbonnementSuiteController(($container->privates['App\\Repository\\JoueurRepository'] ?? $container->load('getJoueurRepositoryService')), ($container->privates['App\\Repository\\AbonnementRepository'] ?? $container->load('getAbonnementRepositoryService')), ($container->privates['App\\Repository\\DisciplineRepository'] ?? $container->load('getDisciplineRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Backend\\BackendAbonnementSuiteController', $container));

        return $instance;
    }
}
