<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackendAdhesionControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Backend\BackendAdhesionController' shared autowired service.
     *
     * @return \App\Controller\Backend\BackendAdhesionController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        $container->services['App\\Controller\\Backend\\BackendAdhesionController'] = $instance = new \App\Controller\Backend\BackendAdhesionController(new \App\Service\GestionAdherent(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), $a, ($container->privates['App\\Repository\\CompagnieRepository'] ?? $container->load('getCompagnieRepositoryService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService'))), $a);

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Backend\\BackendAdhesionController', $container));

        return $instance;
    }
}
