<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackendParticipantControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Backend\BackendParticipantController' shared autowired service.
     *
     * @return \App\Controller\Backend\BackendParticipantController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Backend\\BackendParticipantController'] = $instance = new \App\Controller\Backend\BackendParticipantController(($container->privates['App\\Repository\\JoueurRepository'] ?? $container->load('getJoueurRepositoryService')), ($container->privates['App\\Service\\AllRepositories'] ?? $container->load('getAllRepositoriesService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Backend\\BackendParticipantController', $container));

        return $instance;
    }
}
