<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtudiantTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\EtudiantType' shared autowired service.
     *
     * @return \App\Form\EtudiantType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\EtudiantType'] = new \App\Form\EtudiantType();
    }
}
