<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontendMembreControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Frontend\FrontendMembreController' shared autowired service.
     *
     * @return \App\Controller\Frontend\FrontendMembreController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Frontend\\FrontendMembreController'] = $instance = new \App\Controller\Frontend\FrontendMembreController(($container->privates['App\\Repository\\MembreRepository'] ?? $container->load('getMembreRepositoryService')), ($container->privates['App\\Repository\\AbonnementRepository'] ?? $container->load('getAbonnementRepositoryService')), ($container->privates['App\\Repository\\JoueurRepository'] ?? $container->load('getJoueurRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Frontend\\FrontendMembreController', $container));

        return $instance;
    }
}
