<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontendScientifiqueControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Frontend\FrontendScientifiqueController' shared autowired service.
     *
     * @return \App\Controller\Frontend\FrontendScientifiqueController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Frontend\\FrontendScientifiqueController'] = $instance = new \App\Controller\Frontend\FrontendScientifiqueController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Frontend\\FrontendScientifiqueController', $container));

        return $instance;
    }
}
