<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontendFactureControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Frontend\FrontendFactureController' shared autowired service.
     *
     * @return \App\Controller\Frontend\FrontendFactureController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Frontend\\FrontendFactureController'] = $instance = new \App\Controller\Frontend\FrontendFactureController(($container->privates['App\\Repository\\AbonnementRepository'] ?? $container->load('getAbonnementRepositoryService')), ($container->privates['App\\Repository\\MembreRepository'] ?? $container->load('getMembreRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Frontend\\FrontendFactureController', $container));

        return $instance;
    }
}
