<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInsertDisciplineCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\InsertDisciplineCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\InsertDisciplineCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:insert-discipline', [], 'Insertion des disciplines dans la base de données', false, #[\Closure(name: 'App\\Command\\InsertDisciplineCommand')] fn (): \App\Command\InsertDisciplineCommand => ($container->privates['App\\Command\\InsertDisciplineCommand'] ?? $container->load('getInsertDisciplineCommandService')));
    }
}
