<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInsertDisciplineCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\InsertDisciplineCommand' shared autowired service.
     *
     * @return \App\Command\InsertDisciplineCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\InsertDisciplineCommand'] = $instance = new \App\Command\InsertDisciplineCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\DisciplineRepository'] ?? $container->load('getDisciplineRepositoryService')));

        $instance->setName('app:insert-discipline');
        $instance->setDescription('Insertion des disciplines dans la base de données');

        return $instance;
    }
}
