<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJoueurTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\JoueurType' shared autowired service.
     *
     * @return \App\Form\JoueurType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\JoueurType'] = new \App\Form\JoueurType();
    }
}
