<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipantTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ParticipantType' shared autowired service.
     *
     * @return \App\Form\ParticipantType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ParticipantType'] = new \App\Form\ParticipantType();
    }
}
