<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipantRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ParticipantRepository' shared autowired service.
     *
     * @return \App\Repository\ParticipantRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ParticipantRepository'] = new \App\Repository\ParticipantRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
