<?php

namespace ContainerZ6wCJRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilitiesService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\Utilities' shared autowired service.
     *
     * @return \App\Service\Utilities
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Utilities'] = new \App\Service\Utilities(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\SponsorRepository'] ?? $container->load('getSponsorRepositoryService')));
    }
}
