<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Discipline extends \App\Entity\Discipline implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Complementaire' => [parent::class, 'Complementaire', null],
        "\0".parent::class."\0".'abonnements' => [parent::class, 'abonnements', null],
        "\0".parent::class."\0".'competirs' => [parent::class, 'competirs', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'joueur' => [parent::class, 'joueur', null],
        "\0".parent::class."\0".'joueurs' => [parent::class, 'joueurs', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null],
        'Complementaire' => [parent::class, 'Complementaire', null],
        'abonnements' => [parent::class, 'abonnements', null],
        'competirs' => [parent::class, 'competirs', null],
        'id' => [parent::class, 'id', null],
        'joueur' => [parent::class, 'joueur', null],
        'joueurs' => [parent::class, 'joueurs', null],
        'slug' => [parent::class, 'slug', null],
        'titre' => [parent::class, 'titre', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
