<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Joueur extends \App\Entity\Joueur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'abonnement' => [parent::class, 'abonnement', null],
        "\0".parent::class."\0".'carte' => [parent::class, 'carte', null],
        "\0".parent::class."\0".'contact' => [parent::class, 'contact', null],
        "\0".parent::class."\0".'discipline' => [parent::class, 'discipline', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'licence' => [parent::class, 'licence', null],
        "\0".parent::class."\0".'matricule' => [parent::class, 'matricule', null],
        "\0".parent::class."\0".'media' => [parent::class, 'media', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'prenoms' => [parent::class, 'prenoms', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        'abonnement' => [parent::class, 'abonnement', null],
        'carte' => [parent::class, 'carte', null],
        'contact' => [parent::class, 'contact', null],
        'discipline' => [parent::class, 'discipline', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'licence' => [parent::class, 'licence', null],
        'matricule' => [parent::class, 'matricule', null],
        'media' => [parent::class, 'media', null],
        'nom' => [parent::class, 'nom', null],
        'prenoms' => [parent::class, 'prenoms', null],
        'slug' => [parent::class, 'slug', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
