<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Compagnie extends \App\Entity\Compagnie implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'abonnements' => [parent::class, 'abonnements', null],
        "\0".parent::class."\0".'contact' => [parent::class, 'contact', null],
        "\0".parent::class."\0".'dg' => [parent::class, 'dg', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'membres' => [parent::class, 'membres', null],
        "\0".parent::class."\0".'participants' => [parent::class, 'participants', null],
        "\0".parent::class."\0".'representant' => [parent::class, 'representant', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null],
        'abonnements' => [parent::class, 'abonnements', null],
        'contact' => [parent::class, 'contact', null],
        'dg' => [parent::class, 'dg', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'membres' => [parent::class, 'membres', null],
        'participants' => [parent::class, 'participants', null],
        'representant' => [parent::class, 'representant', null],
        'slug' => [parent::class, 'slug', null],
        'titre' => [parent::class, 'titre', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
