<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Abonnement extends \App\Entity\Abonnement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'annee' => [parent::class, 'annee', null],
        "\0".parent::class."\0".'compagnie' => [parent::class, 'compagnie', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'disciplines' => [parent::class, 'disciplines', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'joueurs' => [parent::class, 'joueurs', null],
        "\0".parent::class."\0".'justificatif' => [parent::class, 'justificatif', null],
        "\0".parent::class."\0".'media' => [parent::class, 'media', null],
        "\0".parent::class."\0".'montant' => [parent::class, 'montant', null],
        "\0".parent::class."\0".'reference' => [parent::class, 'reference', null],
        "\0".parent::class."\0".'restantJoueur' => [parent::class, 'restantJoueur', null],
        "\0".parent::class."\0".'solde' => [parent::class, 'solde', null],
        "\0".parent::class."\0".'totalJoueur' => [parent::class, 'totalJoueur', null],
        'annee' => [parent::class, 'annee', null],
        'compagnie' => [parent::class, 'compagnie', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'disciplines' => [parent::class, 'disciplines', null],
        'id' => [parent::class, 'id', null],
        'joueurs' => [parent::class, 'joueurs', null],
        'justificatif' => [parent::class, 'justificatif', null],
        'media' => [parent::class, 'media', null],
        'montant' => [parent::class, 'montant', null],
        'reference' => [parent::class, 'reference', null],
        'restantJoueur' => [parent::class, 'restantJoueur', null],
        'solde' => [parent::class, 'solde', null],
        'totalJoueur' => [parent::class, 'totalJoueur', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
