<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Adhesion extends \App\Entity\Adhesion implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null],
        "\0".parent::class."\0".'civilite' => [parent::class, 'civilite', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'entreprise' => [parent::class, 'entreprise', null],
        "\0".parent::class."\0".'fonction' => [parent::class, 'fonction', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'media' => [parent::class, 'media', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'prenoms' => [parent::class, 'prenoms', null],
        "\0".parent::class."\0".'reference' => [parent::class, 'reference', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null],
        'adresse' => [parent::class, 'adresse', null],
        'civilite' => [parent::class, 'civilite', null],
        'email' => [parent::class, 'email', null],
        'entreprise' => [parent::class, 'entreprise', null],
        'fonction' => [parent::class, 'fonction', null],
        'id' => [parent::class, 'id', null],
        'media' => [parent::class, 'media', null],
        'nom' => [parent::class, 'nom', null],
        'prenoms' => [parent::class, 'prenoms', null],
        'reference' => [parent::class, 'reference', null],
        'slug' => [parent::class, 'slug', null],
        'statut' => [parent::class, 'statut', null],
        'telephone' => [parent::class, 'telephone', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
