<?php

namespace ContainerQaPxsSh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BsnftZdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BsnftZd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BsnftZd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'adhesionRepository' => ['privates', 'App\\Repository\\AdhesionRepository', 'getAdhesionRepositoryService', true],
        ], [
            'adhesionRepository' => 'App\\Repository\\AdhesionRepository',
        ]);
    }
}
