<?php

namespace ContainerQaPxsSh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A9S0YmTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A9S0YmT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A9S0YmT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'joueur' => ['privates', '.errored..service_locator.A9S0YmT.App\\Entity\\Joueur', NULL, 'Cannot autowire service ".service_locator.A9S0YmT": it needs an instance of "App\\Entity\\Joueur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'joueur' => 'App\\Entity\\Joueur',
        ]);
    }
}
