<?php

namespace ContainerQaPxsSh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RptGKcSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RptGKcS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RptGKcS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'participantRepository' => ['privates', 'App\\Repository\\ParticipantRepository', 'getParticipantRepositoryService', true],
        ], [
            'participantRepository' => 'App\\Repository\\ParticipantRepository',
        ]);
    }
}
