<?php

namespace ContainerQaPxsSh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kqq7UYAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kqq7UYA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kqq7UYA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'discipline' => ['privates', '.errored..service_locator.kqq7UYA.App\\Entity\\Discipline', NULL, 'Cannot autowire service ".service_locator.kqq7UYA": it needs an instance of "App\\Entity\\Discipline" but this type has been excluded in "config/services.yaml".'],
            'disciplineRepository' => ['privates', 'App\\Repository\\DisciplineRepository', 'getDisciplineRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'discipline' => 'App\\Entity\\Discipline',
            'disciplineRepository' => 'App\\Repository\\DisciplineRepository',
            'entityManager' => '?',
        ]);
    }
}
