<?php

namespace ContainerQaPxsSh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KTK5GqiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kTK5Gqi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kTK5Gqi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'adhesion' => ['privates', '.errored..service_locator.kTK5Gqi.App\\Entity\\Adhesion', NULL, 'Cannot autowire service ".service_locator.kTK5Gqi": it needs an instance of "App\\Entity\\Adhesion" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'adhesion' => 'App\\Entity\\Adhesion',
            'entityManager' => '?',
        ]);
    }
}
