<?php

namespace ContainerQaPxsSh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TTVZYiEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TTVZYiE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TTVZYiE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'compagnie' => ['privates', '.errored..service_locator.TTVZYiE.App\\Entity\\Compagnie', NULL, 'Cannot autowire service ".service_locator.TTVZYiE": it needs an instance of "App\\Entity\\Compagnie" but this type has been excluded in "config/services.yaml".'],
            'compagnieRepository' => ['privates', 'App\\Repository\\CompagnieRepository', 'getCompagnieRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'compagnie' => 'App\\Entity\\Compagnie',
            'compagnieRepository' => 'App\\Repository\\CompagnieRepository',
            'entityManager' => '?',
        ]);
    }
}
