<?php

namespace ContainerQaPxsSh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AgszzxfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.agszzxf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.agszzxf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'adhesion' => ['privates', '.errored..service_locator.agszzxf.App\\Entity\\Adhesion', NULL, 'Cannot autowire service ".service_locator.agszzxf": it needs an instance of "App\\Entity\\Adhesion" but this type has been excluded in "config/services.yaml".'],
        ], [
            'adhesion' => 'App\\Entity\\Adhesion',
        ]);
    }
}
