<?php

namespace ContainerQaPxsSh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdhesion3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kTK5Gqi.App\Entity\Adhesion' shared service.
     *
     * @return \App\Entity\Adhesion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kTK5Gqi": it needs an instance of "App\\Entity\\Adhesion" but this type has been excluded in "config/services.yaml".');
    }
}
