<?php

namespace ContainerQaPxsSh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackendParticipantControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Backend\BackendParticipantController' shared autowired service.
     *
     * @return \App\Controller\Backend\BackendParticipantController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Backend'.\DIRECTORY_SEPARATOR.'BackendParticipantController.php';

        $container->services['App\\Controller\\Backend\\BackendParticipantController'] = $instance = new \App\Controller\Backend\BackendParticipantController(($container->privates['App\\Repository\\JoueurRepository'] ?? $container->load('getJoueurRepositoryService')), ($container->privates['App\\Service\\AllRepositories'] ?? $container->load('getAllRepositoriesService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Backend\\BackendParticipantController', $container));

        return $instance;
    }
}
