<?php

namespace ContainerQaPxsSh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackendJoueurControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Backend\BackendJoueurController' shared autowired service.
     *
     * @return \App\Controller\Backend\BackendJoueurController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Backend'.\DIRECTORY_SEPARATOR.'BackendJoueurController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'GestionMedia.php';

        $container->services['App\\Controller\\Backend\\BackendJoueurController'] = $instance = new \App\Controller\Backend\BackendJoueurController(($container->privates['App\\Repository\\JoueurRepository'] ?? $container->load('getJoueurRepositoryService')), ($container->privates['App\\Service\\AllRepositories'] ?? $container->load('getAllRepositoriesService')), ($container->privates['App\\Repository\\AbonnementRepository'] ?? $container->load('getAbonnementRepositoryService')), ($container->privates['App\\Service\\GestionMedia'] ??= new \App\Service\GestionMedia((\dirname(__DIR__, 4).'/public/upload/participants'), (\dirname(__DIR__, 4).'/public/upload/adhesion'), (\dirname(__DIR__, 4).'/public/upload/sponsors'))));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Backend\\BackendJoueurController', $container));

        return $instance;
    }
}
