<?php

namespace ContainerQaPxsSh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontendFactureControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Frontend\FrontendFactureController' shared autowired service.
     *
     * @return \App\Controller\Frontend\FrontendFactureController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Frontend'.\DIRECTORY_SEPARATOR.'FrontendFactureController.php';

        $container->services['App\\Controller\\Frontend\\FrontendFactureController'] = $instance = new \App\Controller\Frontend\FrontendFactureController(($container->privates['App\\Repository\\AbonnementRepository'] ?? $container->load('getAbonnementRepositoryService')), ($container->privates['App\\Repository\\MembreRepository'] ?? $container->load('getMembreRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Frontend\\FrontendFactureController', $container));

        return $instance;
    }
}
