<?php

namespace ContainerQaPxsSh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInsertDisciplineCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\InsertDisciplineCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\InsertDisciplineCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:insert-discipline', [], 'Insertion des disciplines dans la base de données', false, #[\Closure(name: 'App\\Command\\InsertDisciplineCommand')] fn (): \App\Command\InsertDisciplineCommand => ($container->privates['App\\Command\\InsertDisciplineCommand'] ?? $container->load('getInsertDisciplineCommandService')));
    }
}
