<?php

namespace ContainerQaPxsSh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInsertDisciplineCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\InsertDisciplineCommand' shared autowired service.
     *
     * @return \App\Command\InsertDisciplineCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'InsertDisciplineCommand.php';

        $container->privates['App\\Command\\InsertDisciplineCommand'] = $instance = new \App\Command\InsertDisciplineCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\DisciplineRepository'] ?? $container->load('getDisciplineRepositoryService')));

        $instance->setName('app:insert-discipline');
        $instance->setDescription('Insertion des disciplines dans la base de données');

        return $instance;
    }
}
