<?php

namespace ContainerQaPxsSh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJoueurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.A9S0YmT.App\Entity\Joueur' shared service.
     *
     * @return \App\Entity\Joueur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.A9S0YmT": it needs an instance of "App\\Entity\\Joueur" but this type has been excluded in "config/services.yaml".');
    }
}
